services:

  mysql:
    image: mysql:8.0
    container_name: airq-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s


  backend:
    image: ${DOCKERHUB_USERNAME}/air-quality-backend:${IMAGE_TAG}
    container_name: airq-backend
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8000:8000"


  frontend:
    image: ${DOCKERHUB_USERNAME}/air-quality-frontend:${IMAGE_TAG}
    container_name: airq-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"


volumes:
  mysql_data:
